"""Inicial

Revision ID: 993c3743e09d
Revises: 
Create Date: 2022-06-18 18:47:58.168427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993c3743e09d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
