"""Add coluna Tamanhos

Revision ID: d79e46c97729
Revises: 993c3743e09d
Create Date: 2022-06-18 18:51:55.643099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79e46c97729'
down_revision = '993c3743e09d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Produto', sa.Column('tamanhos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Produto', 'tamanhos')
    # ### end Alembic commands ###
